/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillkorRouteImport } from './routes/villkor'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as MolkomsPizzeriaRouteImport } from './routes/molkoms-pizzeria'
import { Route as MenyRouteImport } from './routes/meny'
import { Route as KontaktaOssRouteImport } from './routes/kontakta-oss'
import { Route as InterntRouteImport } from './routes/internt'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as IndexRouteImport } from './routes/index'

const VillkorRoute = VillkorRouteImport.update({
  id: '/villkor',
  path: '/villkor',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const MolkomsPizzeriaRoute = MolkomsPizzeriaRouteImport.update({
  id: '/molkoms-pizzeria',
  path: '/molkoms-pizzeria',
  getParentRoute: () => rootRouteImport,
} as any)
const MenyRoute = MenyRouteImport.update({
  id: '/meny',
  path: '/meny',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktaOssRoute = KontaktaOssRouteImport.update({
  id: '/kontakta-oss',
  path: '/kontakta-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const InterntRoute = InterntRouteImport.update({
  id: '/internt',
  path: '/internt',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catering': typeof CateringRoute
  '/faq': typeof FaqRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/internt': typeof InterntRoute
  '/kontakta-oss': typeof KontaktaOssRoute
  '/meny': typeof MenyRoute
  '/molkoms-pizzeria': typeof MolkomsPizzeriaRoute
  '/om-oss': typeof OmOssRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/villkor': typeof VillkorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catering': typeof CateringRoute
  '/faq': typeof FaqRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/internt': typeof InterntRoute
  '/kontakta-oss': typeof KontaktaOssRoute
  '/meny': typeof MenyRoute
  '/molkoms-pizzeria': typeof MolkomsPizzeriaRoute
  '/om-oss': typeof OmOssRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/villkor': typeof VillkorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catering': typeof CateringRoute
  '/faq': typeof FaqRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/internt': typeof InterntRoute
  '/kontakta-oss': typeof KontaktaOssRoute
  '/meny': typeof MenyRoute
  '/molkoms-pizzeria': typeof MolkomsPizzeriaRoute
  '/om-oss': typeof OmOssRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/villkor': typeof VillkorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catering'
    | '/faq'
    | '/integritetspolicy'
    | '/internt'
    | '/kontakta-oss'
    | '/meny'
    | '/molkoms-pizzeria'
    | '/om-oss'
    | '/sitemap.xml'
    | '/villkor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catering'
    | '/faq'
    | '/integritetspolicy'
    | '/internt'
    | '/kontakta-oss'
    | '/meny'
    | '/molkoms-pizzeria'
    | '/om-oss'
    | '/sitemap.xml'
    | '/villkor'
  id:
    | '__root__'
    | '/'
    | '/catering'
    | '/faq'
    | '/integritetspolicy'
    | '/internt'
    | '/kontakta-oss'
    | '/meny'
    | '/molkoms-pizzeria'
    | '/om-oss'
    | '/sitemap.xml'
    | '/villkor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CateringRoute: typeof CateringRoute
  FaqRoute: typeof FaqRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  InterntRoute: typeof InterntRoute
  KontaktaOssRoute: typeof KontaktaOssRoute
  MenyRoute: typeof MenyRoute
  MolkomsPizzeriaRoute: typeof MolkomsPizzeriaRoute
  OmOssRoute: typeof OmOssRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VillkorRoute: typeof VillkorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villkor': {
      id: '/villkor'
      path: '/villkor'
      fullPath: '/villkor'
      preLoaderRoute: typeof VillkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/molkoms-pizzeria': {
      id: '/molkoms-pizzeria'
      path: '/molkoms-pizzeria'
      fullPath: '/molkoms-pizzeria'
      preLoaderRoute: typeof MolkomsPizzeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meny': {
      id: '/meny'
      path: '/meny'
      fullPath: '/meny'
      preLoaderRoute: typeof MenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakta-oss': {
      id: '/kontakta-oss'
      path: '/kontakta-oss'
      fullPath: '/kontakta-oss'
      preLoaderRoute: typeof KontaktaOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internt': {
      id: '/internt'
      path: '/internt'
      fullPath: '/internt'
      preLoaderRoute: typeof InterntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CateringRoute: CateringRoute,
  FaqRoute: FaqRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  InterntRoute: InterntRoute,
  KontaktaOssRoute: KontaktaOssRoute,
  MenyRoute: MenyRoute,
  MolkomsPizzeriaRoute: MolkomsPizzeriaRoute,
  OmOssRoute: OmOssRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VillkorRoute: VillkorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
